### ISSUE TITLE
ResultTime observations must be unique

### ISSUE THREAD

**Issue by elb29** [52North/sensorweb-server-sta#120]
Hello, 
I'm trying to use your solution and when I try to post my data to my instance of the 52North-sta-server, 

(For example those observations (in a Datastream) : 

`'Observations': [{'phenomenonTime': '2020-01-14T08:16:30Z', 'resultTime': '2020-01-14T08:16:30Z', 'result': '8.2', 'FeatureOfInterest': {'@iot.id': '6901189-24.774656.2218'}}, {'phenomenonTime': '2020-01-14T08:16:30Z', 'resultTime': '2020-01-14T08:16:30Z', 'result': '14.8', 'FeatureOfInterest': {'@iot.id': '6901189-24.774656.2218'}}]` )

I get this error : 

`{"timestamp":1597827532131,"error":"javax.persistence.PersistenceException","message":"ERROR: duplicate key value violates unique constraint \"un_observation_identity\"\n  Detail: Key (value_type, fk_dataset_id, sampling_time_start, sampling_time_end, result_time, vertical_from, vertical_to)=(quantity, 1647, 2020-01-14 08:16:30, 2020-01-14 08:16:30, 2020-01-14 08:16:30, 0.0000000000, 0.0000000000) already exists."}`

What I understand from that is that the server doesn't accept two observations with the same resultTime. It seems to be that as it works when I randomly put differents resultTime for the two observations but could you confirm me that this is the correct meaning of this error and that it's the desired behaviour and not a bug. 

Thank you.

**Comment by SpeckiJ** [comment]
Hi,

Thanks for reporting this undocumented behaviour. This is indeed a limitation of our implementation (specifically restrictions on our database model) and is intentional. The combination of resultTime+phenomenonTime must be unique, else we reject the Observation (we have to work on the error message formatting I have to admit).

The idea behind this restriction is that there is no case where this would be valid data. The same timestamps mean that a Sensor has measured the same Feature twice in the same timestamp and has gotten different results.

Is there a specific usecase where you need this "feature" of multiple observations inside the same Datastream which have different values but the exact same timestamps?

**Comment by SpeckiJ** [comment]
I have now documented this behaviour in our [GitHub Wiki](https://github.com/52North/sensorweb-server-sta/wiki/Documentation:-52N-specific-features) :+1:

**Comment by elb29** [comment]
Ok thank you for this quick and clear answer. 

Yes there's a specific case where I need this feature. In fact the data I'm dealing with are from a special type of data, we call them a "Profile". With a "Profile", we want to "map" different physical observations (temperature, salinity...) in function of the pressure (which represents the depth in the ocean). In fact we put an elongated sensor in the sea and this captor measures at different depths and at the same time both the physical observations and the pressure. 
So I'm here in the case mentionned above as the captor is taking at the exact time many pressures, temperatures and salinity for example, to have a graph like this for instance : 

![ocean-55](https://user-images.githubusercontent.com/45095743/90652954-e8cfbe80-e23e-11ea-8a2c-a5f643567835.gif)

This data is then stored in csv files from which we process them into the SensorThings API in order to feed the STA-server.

**Comment by SpeckiJ** [comment]
That is indeed a valid use-case, unfortunately the STA does not define handling for Profile data yet.

For now I would suggest a slightly different model for storing the data (circumvent our database restrictions by using seperate Features):

Right now you are using the same FeatureOfInterest for all observations, despite them actually being in different depths and therefore actually measuring at different locations. I would suggest splitting up the FeatureOfInterest into the seperate depths where the values are measured (e.g. 1m/2m/10m/100m), and linking the Observation with the corresponding FeatureOfInterest. When the Observations have different FeatureOfInterest they can have the same timestamps. This also allows for nice querying:

Get all Observations at a specific time (and their associated Feature to see where they are measuring): `/Observations?$expand=FeatureOfInterest($select=id,name)&$filter=phenomenonTime eq 2020-01-14T08:16:30Z`

Get all Observations at a specific depth over time:
`/Observations?$filter=FeatureOfInterest/id eq 'Pressure-10m'`

If you can't predefine the Features (e.g. if you do not know where the sensor will be beforehand), you can use deep-insert and generate the Features together with the Observations.

**Edit:**
This works around the issue of having multiple (e.g. salinity) measurements at the same time in the same Datastream. In the STA Measurements for Temperature and Salinity should be in different Datastreams (as they have a different ObservedProperty) and the issue of parallel observations being inserted therefore does not occur there.

**Comment by elb29** [comment]
Thank you very much for your suggestion, I've just tested it and it seems to work fine. 
As I already use different Datastreams for each ObservedProperty, I just had to add the depth in the FeaturesOfInterest of my Observations and now the server accept them even if they have the same couple PhenomenonTime/ResultTime.  

My observations are just looking like that now : 
`{'phenomenonTime': '2020-01-14T08:16:30Z',
 'resultTime': '2020-01-14T08:16:30Z',
 'result': '9.289',
 'FeatureOfInterest': {'@iot.id': '6901189-24.774656.22188.2',
                                'name': '6901189-24.774656.22188.2',
                                'description': 'foi 6901189',
                                'encodingType': 'application/vnd.geo+json',
                                'feature': {'type': 'Feature',
                                               'geometry': {'type': 'Point',
                                                                  'coordinates': [-24.7746, 56.2218, 8.2]}
                                               }
                                }
}`

Thank you very much for your help and your quick answers!

**Comment by SpeckiJ** [comment]
We have looked at your specific use-case further and found that unfortunately the way we store data using the workaround I described above is very inefficient. Internally a new `dataset` is created every for every new FOI, as this is needed for interopatibilty with the SOS and 52N Helgoland API.

Since v2.2.0 we therefore support setting the vertical extend of Observations via Observations->Parameters. An example for this can be seen below:
```
{
	"phenomenonTime": "2012-06-26T03:43:02-0600",
	"result": 70.4,
       "parameters": [
           {"name": "verticalFromTo", "value": 121}
        ],
	"Datastream": {
		"@iot.id": "<datastreamId>"
	},
	"FeatureOfInterest": {
		"@iot.id": "<foiId>"
	}
}
```

I have also documented this in our wiki here: https://github.com/52North/sensorweb-server-sta/wiki/Documentation:-52N-specific-features#optional-support-for-profileobservations

**Comment by elb29** [comment]
Thank you for this update, though when I try to post Observations that look like that with the latest instance of your docker image , for instance : 
```
{
	'phenomenonTime': '2018-11-27T15:09:17Z',
 	'resultTime': '2018-11-27T15:09:17Z',
 	'parameters': [{'name': 'verticalFromTo', 'value': 800.1}],
	'result': 10.684,
 	'FeatureOfInterest': {'@iot.id': '2902402-5.040044.1540'}
}
```
I again get the error : 

`{"timestamp":1598857852596,"error":"javax.persistence.PersistenceException","message":"ERROR: duplicate key value violates unique constraint \"un_observation_identity\"\n  Detail: Key (value_type, fk_dataset_id, sampling_time_start, sampling_time_end, result_time, vertical_from, vertical_to)=(quantity, 29, 2018-11-20 09:28:20, 2018-11-20 09:28:20, 2018-11-20 09:28:20, 0.0000000000, 0.0000000000) already exists."}
`


It seems, after some tests, that the previous exemple you posted works because you didn't fill in the resultTime and that the server accepts to have multiple observations with the same couple phenomenonTime/resultTime where resultTime is `null`

**Comment by CarstenHollmann** [comment]
Hi @elb29 ,

there is a mistake in the example. The configuration parameter key `verticalFromTo` instead of the value `vertical` was used.

If you use the configuration parameter value `vertical` like in the example below, the insertion of the observations works:

```
{
       "phenomenonTime": "2012-06-26T03:43:02-0600",
       "result": 70.4,
       "parameters": [
           {"name": "vertical", "value": 121}
        ],
	"Datastream": {
		"@iot.id": "<datastreamId>"
	},
	"FeatureOfInterest": {
		"@iot.id": "<foiId>"
	}
}
```

**Comment by elb29** [comment]
Hello, 
I am sorry but even after trying to change the `name` value from `verticalFromTo` to `vertical` the server still refuses my Observations and returns the same error.

**Comment by SpeckiJ** [comment]
This does seem wierd - we just tested it on the `latest` tag and it works for us.

Can you verify that you are running version 2.0+? We have a custom endpoint `/version` to give out debug information just for this use-case.
A screenshot/copy-paste of the response from this endpoint would be helpful to pinpoint the exact commit that causes this issue.

**Comment by elb29** [comment]
This is the response I get from the endpoint `/version`  :
```
{
git.repository: "git@github.com:52North/sensorweb-server-sta.git",
git.lastCommitDate: "2020-08-28 09:39:49+0000",
git.path: "v2.2.1",
git.lastCommitMessage: "[maven-release-plugin] prepare release v2.2.1",
git.revision: "370314aad59191553906cb02a1b64c4bd2f6822e",
project.name: "52North SensorThingsAPI",
project.version: "2.2.1",
project.time: "2020-08-28T09:44:13.849Z",
git.builddate: "2020-08-28 09:44:59+0000"
}
```

**Comment by Kundanagrawalofficial** [comment]
ok will try
