### ISSUE TITLE
Cannot compile project

### ISSUE THREAD

**Issue by digimatspa** [52North/sensorweb-server-sta#148]
Project build fails because the following dependencies cannot be found in the maven repository

https://github.com/52North/sensorweb-server-sta/blob/285c1bcfbed690b976ac22393210e3e436491048/pom.xml#L41-L42

Thank you

**Comment by SpeckiJ** [comment]
As we are currently in active development, we use SNAPSHOT Versions of the dependencies that are also under active development.
To build the `develop` branch, the SNAPSHOT versions of `db-model` and `arctic-sea` need to be installed manually from the following repositories:

https://github.com/52North/sensorweb-server-db-model/tree/refactor/entity_specific_parameters

https://github.com/SpeckiJ/arctic-sea/tree/feature/sensorML20EventDecoding


If you just want a running version (not compile it yourself) we provide ready-to-run packages via Github Releases:

https://github.com/52North/sensorweb-server-sta/releases

We are working on a final release of v3.x (STA 1.1 Support) in the next 2 weeks, an initial draft is available as a pre-release (docker image will be available once v3.x is fully released).
