### ISSUE TITLE
Posting of Datastream leads to NullPointerException

### ISSUE THREAD

**Issue by emdekatharina** [52North/sensorweb-server-sta#192]
I run a sensorweb-server-sta as a Docker container and receive a NullPointerException when I try to post a simple Datastream. I am putting the stacktrace into the attachment, along with the used datastream json.
Please let me know, if you need anything else to reproduce the Exception
[datastream_json.txt](https://github.com/52North/sensorweb-server-sta/files/7676423/datastream_json.txt)
[stacktrace_sta_datsatream.txt](https://github.com/52North/sensorweb-server-sta/files/7676424/stacktrace_sta_datsatream.txt)
.

**Comment by SpeckiJ** [comment]
Thanks for the report - what version of the Dockerfile are you using? based on the stacktrace it looks like you are using version 3.1 which is missing some critical bugfixes.

I just noticed that the `latest` tag was not properly updated. I have updated it now to point to the latest version. Can you try again either using the image ` 52north/sensorweb-server-sta:3.0.3-PR.3` or pull again if you use the `latest` tag and see if the issue persists?

**Comment by emdekatharina** [comment]
Thanks for your quick response - pulling the latest image solved the issue!
