### ISSUE TITLE
@iot.nextLink missing when using parameter $count

### ISSUE THREAD

**Issue by EnocMartinez** [52North/sensorweb-server-sta#304]
I've found a minor bug in the SensorThings API. When I'm doing a GET query on /Observations with $count=true the response from the server does not include the @iot.nextLink field in the response. When I remove the count I get the nextLink correctly.

I guess this behavior is not expected, since a user would assume that there isn't more data when the nextLink is not present in the response.

Best regards,

Enoc

**Comment by EnocMartinez** [comment]
I've noticed that the API has the same behavior with skip, when $skip is set the response doesn't include @iot.nextLink field.

**Comment by SpeckiJ** [comment]
Hello,

thanks for the report - that is indeed confusing behaviour. I will look into it

**Comment by SpeckiJ** [comment]
fixed via https://github.com/52North/sensorweb-server-sta/commit/d8795ad9eb4c69e379275a9480cf59827b323ec7
