### ISSUE TITLE
Datastream considered invalid on empty unit values

### ISSUE THREAD

**Issue by ridoo** [52North/sensorweb-server-sta#81]
## Problem:

POSTing the following payload to `/sta/Thing/` of an empty STA instance:

```json
{
  "name": "thingy-thing",
  "description": "Whatever",
  "properties": {
    "uri": "https://some.url"
  },
  "Locations": [
    {
      "name": "Position",
      "description": "Thing location",
      "encodingType": "application/vnd.geo+json",
      "location": {
        "type": "Point",
        "coordinates": [
          23.094,
          42.361
        ]
      }
    }
  ],
  "Datastreams": [
    {
      "name": "Thing-stream",
      "description": "Stream description",
      "observationType": "http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_CategoryObservation",
      "unitOfMeasurement": {
        "name": null,
        "symbol": null,
        "definition": null
      },
      "ObservedProperty": {
        "name": "Taxon",
        "description": "The canonical name of the observed species",
        "definition": "http://some.url"
      },
      "Sensor": {
        "name": "Citizen Scientist",
        "description": "Person sharing individual observations to the public for scientific use",
        "encodingType": "text/html",
        "metadata": "https://some.url"
      }
    }
  ]
}
```

## Actual:
The STA responds with an `FULLInvalid Entity` error, in particular the response message is: 

```
FULLInvalid Entity. Not all required properties present! Missing: unitOfMeasurement->nameREFERENCEInvalid Entity. Only @iot.id may be present when referencing an existing entity!
```

## Expected:
The problem seems to be the empty `unitOfMeasurement`:

```json
"unitOfMeasurement": {
  "name": null,
  "symbol": null,
  "definition": null
}
```

Here is the code raising the error:

https://github.com/52North/sensorweb-server-sta/blob/5ad57e84a39816ca681a1df6d8a187d0608e4b20/core/src/main/java/org/n52/sta/serdes/json/JSONDatastream.java#L104-L106

However, the [STA specification](http://docs.opengeospatial.org/is/15-078r6/15-078r6.html#table_10) allows the definition of an /empty/ `unitOfMeasurement`. This is actually needed for cases where no unit of measurement is available (count/category/unit-less measurements like pH-value, etc.). Passing an empty UoM seems to be rather clunky, but that is what the specification says: 

> Note: When a Datastream does not have a unit of measurement (e.g., a OM_TruthObservation type), the corresponding unitOfMeasurement properties SHALL have null values.

**Comment by SpeckiJ** [comment]
This should be fixed in https://github.com/52North/sensorweb-server-sta/commit/c87fa5587ece66b73770b32eccabc9efc27117e4. Thanks for the report :+1: 

Note: e6c9de3d7925720b4e8f38d4f6eb19e44f58de5c changes the default config to be conforming to the standard (excluding many 52N-STA specific features). Therefore you need to adapt the config to make your `Sensor->encodingType` work
