### ISSUE TITLE
resultTime is ignored when POSTing Observations 

### ISSUE THREAD

**Issue by ridoo** [52North/sensorweb-server-sta#86]
The result time is not being stored (or serialized) when requesting an inserted observation. 

## Reproduce

Take the "Full"-example from the Postman test collection and add a `resultTime` to an observation: 

```
{
	"description": "This an oven with a temperature datastream.",
	"name": "oven",
	"Locations": [
		{
			"name": "CCIT",
			"description": "Calgary Centre for Innovative Technologies",
			"encodingType": "application/vnd.geo+json",
			"location": {
				"type": "Feature",
				"geometry": {
					"type": "Point",
					"coordinates": [
						10,
						10
					]
				}
			}
		}
	],
	"Datastreams": [
		{
			"name": "oven temperature",
			"description": "This is a datastream for an oven’s internal temperature.",
			"unitOfMeasurement": {
				"name": "degree Celsius",
				"symbol": "°C",
				"definition": "http://unitsofmeasure.org/ucum.html#para-30"
			},
			"observationType": "http://www.opengis.net/def/observationType/OGC-OM/2.0/OM_Measurement",
			"observedArea": {
				"type": "Polygon",
				"coordinates": [
					[
						[
							100,
							0
						],
						[
							101,
							0
						],
						[
							101,
							1
						],
						[
							100,
							1
						],
						[
							100,
							0
						]
					]
				]
			},
			"phenomenonTime": "2009-01-11T16:22:25.00Z/2011-08-21T08:32:10.00Z",
			"Observations": [
				{
					"phenomenonTime": "2012-06-26T03:42:02-06:00",
					"resulTime": "2012-06-26T03:42:02-06:00",
					"result": 70.4,
					"FeatureOfInterest": {
						"name": "CCIT #361",
						"description": "This is CCIT #361, Noah’s dad’s office",
						"encodingType": "application/vnd.geo+json",
						"feature": {
							"type": "Feature",
							"geometry": {
								"type": "Polygon",
								"coordinates": [
									[
										[
											100,
											50
										],
										[
											10,
											9
										],
										[
											23,
											4
										],
										[
											100,
											50
										]
									],
									[
										[
											30,
											20
										],
										[
											10,
											4
										],
										[
											4,
											22
										],
										[
											30,
											20
										]
									]
								]
							}
						}
					}
				}
			],
			"ObservedProperty": {
				"name": "DewPoint Temperature",
				"definition": "http://sweet.jpl.nasa.gov/ontology/property.owl#DewPointTemperature",
				"description": "The dewpoint temperature is the temperature ."
			},
			"Sensor": {
				"name": "DS18B20",
				"description": "DS18B20 is an air temperature sensor…",
				"encodingType": "application/pdf",
				"metadata": "http://datasheets.maxim-ic.com/en/ds/DS18B20.pdf"
			}
		}
	]
}
```

The `resultTime` is not available:

```
{
    "@iot.count": 1,
    "value": [
        {
            "@iot.id": "92c537ba-4458-4931-8880-955c00a3708b",
            "@iot.selfLink": "http://localhost:8080/sta/Observations(92c537ba-4458-4931-8880-955c00a3708b)",
            "result": "70.4000000000",
            "resultTime": null,
            "phenomenonTime": "2012-06-26T09:42:02.000Z",
            "resultQuality": null,
            "validTime": null,
            "parameters": [],
            "Datastream@iot.navigationLink": "http://localhost:8080/sta/Observations(92c537ba-4458-4931-8880-955c00a3708b)/Datastream",
            "FeatureOfInterest@iot.navigationLink": "http://localhost:8080/sta/Observations(92c537ba-4458-4931-8880-955c00a3708b)/FeatureOfInterest"
        }
    ]
}
```

**Comment by SpeckiJ** [comment]
This is caused by a flawed logic when distinguishing whether a `resultTime` is set during serialization to JSON here: https://github.com/52North/sensorweb-server-sta/blob/develop/core/src/main/java/org/n52/sta/serdes/ObservationSerDes.java#L136

@CarstenHollmann Is there a nicer way to check if resultTime in the STA is set? IIRC the resultTime needs to be set in the database for SOS compatibility reasons.

**Comment by CarstenHollmann** [comment]
> Is there a nicer way to check if resultTime in the STA is set? 

No. Only adding additional flag columns.
But if the resultTime is not set/null it is the same as phenomenonTime.

> IIRC the resultTime needs to be set in the database for SOS compatibility reasons.

Yes.

**Comment by SpeckiJ** [comment]
>  But if the resultTime is not set/null it is the same as phenomenonTime.

In the STA this might be true, but not conclusive as it may just be the same value that was posted. So from equality we cannot infer that resultTime was posted as `null`.

A database model change is not feasible at the moment, as ist would negatively impact all other 52N Software based on the model (SOS, Helgoland). Therfore we choose to align the STA behaviour with the SOS behaviour by defining that if `resultTime=null` is returned, the resultTime can be seen in the phenomenonTime.

We will document this 52N-STA specific behaviour in the [Wiki](https://github.com/52North/sensorweb-server-sta/wiki/Documentation:-52N-specific-features).

**Comment by CarstenHollmann** [comment]
We will check how complex a database model change would be and what is the impact on other 52N software.

**Comment by SpeckiJ** [comment]
The database model was changed by @CarstenHollmann in https://github.com/52North/sensorweb-server-db-model/commit/27043e91205885bc5469fc147863d23ac0704520 and the change is in the STA in https://github.com/52North/sensorweb-server-sta/commit/ed9b7c28559bc6b755bdcca3c73539d3c7b3cfd6 and https://github.com/52North/sensorweb-server-sta/commit/7e255b0d679b4df299ce26fa9a70fa52c33c453b.

The Docker images `latest` and `2.0.2-SNAPSHOT` are upated accordingly.
